<?

//Create links to all pages for search engines

$All_Pages = array ("Aalen_Kristina.html",



"Architecture.html",



"Art_Friends.html",



"Barcelona.html",



"BrianBerry2.html",

"CastelloDiArthuro.html",

"Charcoal.html",



"Contact.html",



"DoctorFish.html",

"Florence.html",

"Gigs.html",

"Hooga.html",

"Huur_ArthurX.html",



"Litho.html",





"MoonLight.html",

"Movie_Script.html",

"MP3.html",

"Guestbook.php",

"News.html",



"Organic_Villas_Hotels.html",

"OurPrinter.html",

"Paintings.html",



"Poems.html",



"Reactions.html",

"RosaNera.html",

"RudeTonight.html",

"Sculpture_ArthurX.html",

"SignedPrints.html",

"Slogans.html",

"SongText.html",

"Story.html",

"StoryElizabeth.html",



"TextAppDoor.html",

"TextBBB.html",

"TextBored.html",

"TextDeeplyDepressed.html",

"TextDoctorFish.html",

"TextFlowerPicking.html",

"TextGetNo.html",

"TextHooga.html",

"TextIcyBroke.html",

"TextIdealAd.html",

"TextLateAtNight.html",

"TextLostControl.html",

"TextMoonLight.html",

"TextMotherQueen.html",

"TextMountaVista.html",

"TextParisAtNight.html",

"TextPitifull.html",

"TextRude.html",

"TextTalkingToYou.html",

"TextThirteen.html",

"TextTrain.html",

"TextVikings.html",

"TextWaitingFar.html",

"TextWeWantMore.html",

"ThisWeeksGroupie.html",

"Tulp.html",

"Video.html",

"WaterPoortAdam.html");



foreach  ($All_Pages as $Single_HTML)  { echo "<a href=\"". $Single_HTML . "\"></a>";}





echo "</div>";



?>