<?

 //           Create Quote                                          ***********************





$Quote_array =  Array ("If live is like <br> a prison without escape,<p> A Painting is a message to<br> Prisoners after you. <br>Killroy was here.",

                          "A Spy of his own Mind,<br>That's an Artist.",

                          "A Spy of his own Mind,<br>That's an Artist.",

                          "Poorest <br>The slave <br>To no one.",

                          "A friend is like an oracle:<p>Difficult to understand,<br>Impossible to interpret, <br>Slowly sinking away in a boggy marsh.",

                           "I eat dreams and <br> Kill you on the way.",

                           "Thinking is,<br>Directed dreaming.",

                           "What is never dreamed,<br> Will never be.",

                           "The Rich getting richer,<br> Is not wrong.<p>But the Poor getting rich,<br>Is better,<br>Even for the Rich.",

                           "Senseless is the whole life,<br>No way of stopping it.",

                           "For the Pope it's hard to choose between<br>anticonception and war.<p>Because he can't follow the perpetual logic of:<br>Population growth => Famine => War.",

                           "She moved her whole slender body. <br>We were all chasing our dreams.",

                           "To protect a building against decay,<br> You have to turn it into a work of Art.",

                           "If you take the most exclusive palace,<br> And copy it 10 times,<br>It will be the most boring street on earth.",

                           "You can't win, <br> By killing your enemy.",

                           "The Graveyard of Dreams,<br>The place to make friends.") ;



$randomno=rand(0, sizeof($Quote_array)-1 );





echo "<div class='Quote'><p>";

echo "<i><b><br> \" $Quote_array[$randomno] \"</i><p> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ArthurX</b><br><br>";


?>