<?

//      Barcelona July 2006 Array                 ***********************************



 $Barcelona_July_2006_Names =  Array("140_Height_ala-davinyo_Painting.jpg",

"140_Height_Ala_Back_Art.jpg",

"140_Height_Ala_Back_Paints_Crop.jpg",

"140_Height_Ala_Black_Blue_Arthur_Whole.jpg",

"140_Height_Ala_Black_Blue_Face_Hand_Arthur_Crop_Color.jpg",

"140_Height_Ala_Body_Paints.jpg",

"140_Height_Ala_Hand.jpg",

"140_Height_Arc_Bisbe_Building.jpg",

"140_Height_Arc_Bisbe_Building_Barcelona.jpg",

"140_Height_arc_bisbe_Front_Barcelona.jpg",

"140_Height_Arc_Bisbe_Painting_Barcelona_diagonal.jpg",

"140_Height_Arc_Bisbe_Painting_Front.jpg",

"140_Height_ArthurX_Painting_D_Avinyo_Rasta_Dance_Barcelona_2006.jpg",

"140_Height_ArthurX_Paints_Fatty_Catty_and_Cathedral_Seu_Barcelona_2006.jpg",

"140_Height_ArthurX_Paints_Fatty_Catty_Tit.jpg",

"140_Height_ArthurX_Paints_Fille_sur_Pelouse_paris.jpg",

"140_Height_ArthurX_paints_Heart_Paris_hart_pelouse.jpg",

"140_Height_ArthurX_paints_Violist_of_Church_de_la_Merce_in_Barcelona_2006.jpg",

"140_Height_ArthurX_paints_Violist_of_Church_de_la_Merce_Tit_in_Barcelona_2006.jpg",

"140_Height_ArthurX_Sam_Looking_Rasta_Painting_Barcelona.jpg",

"140_Height_Art_Atelier_Painting_Paris_Color.jpg",

"140_Height_Cathedral_ArthurX_Woman_Barcelona.jpg",

"140_Height_Cathedral_Painting_Barcelona.jpg",

"140_Height_Fatty_Catty_Painting_Finished.jpg",

"140_Height_Rasta_Avinyo_Dance.jpg",

"140_Height_Taragons_Platja_Painting_Finished.jpg",

"140_Height_Tarragona_Platja_Model.jpg",

"140_Height_Tarragona_Platja_Photo.jpg",

"140_Height_Violist_Painting_finished.jpg",

"140_Height_vioolmeisje_bij_willemiijn-in-huis_Crop+Color.jpg",

"140_Height_Willemijn_Crop_Color.jpg");




?>