<?

//      Barcelona Array                 ***********************************



 $Barcelona_Names =  Array("Anna_Blauw_Zwart_140_height.jpg",

"Hush_Woman_Cat_Contrast_extra_140_height.jpg",

"Anna_Black_Blue_Purple_140_height.jpg",

"Anna_In_BioShop_Avinyo_and_El_140_height.jpg",

"Anna_No_Green_NoFlash_140_height.jpg",

"Anna_OnlyBlack_140_height.jpg" ,

"Art_Paints_pizzaGirl_Behind_Canvas_140_height.jpg"  ,

"Anna_Outside_Stone_Whole_Painting_140_height.jpg"  ,

"Art_Paints_pizzaGirl_behind_Canvas_2_140_height.jpg"  ,

"Art_Paints_PizzaGirl_Front_Red_140_height.jpg",

"Art_Paints_PizzaGirl_Looking_on_Canvas_140_height.jpg"  ,

"Art_Shows_Lorry_Leg_of_PizzaGirl_140_height.jpg"  ,

"Arthur_painting_Cat_NoFlash_140_height.jpg"  ,

"Arthur_painting_Violist_Black_Flash_140_height.jpg"  ,

"Cathedral_Seu_Photo_140)height.jpg"  ,

"Church_La_Merce_Art+volist_140_height.jpg"  ,

"Crawling_BackWay_Future_140_height.jpg" ,

"El_Hldong_Pizza_Outside_Gallery_140_height.jpg" ,

"El+Palm_140_height.jpg",

"Galeria_Pizza_Girl_SpanishMan_140_height.jpg",

"Little_King_of_Sitges_Blue+Purple_140_height.jpg",

"Lorry_Art_HushHush_140_height.jpg",

"Painting_Cathedral_Seu_140_height.jpg",

"PizzaGirl_Finished_140_height.jpg",

"Nude_Man_Complete_140_height.jpg",

"PizzaGirl_Takes_Break_140_height.jpg",

"Sketch_Anna_Avinyo_140_height.jpg",

"Sketch_Violist_140_height.jpg",

"Tony_Sarah_Art_tlaking_Cat_Flash_140_height.jpg",

"Tony_sitting_in_front_of_Gallery_140_height.jpg",

"Tony_Talking_Arthur_Cat_NoFlash_140_height.jpg",

"Vilolist_All_140_height.jpg",

"Violist_NudeMan_Painting_140_height.jpg",

"Violist_Painting_Finished_Outside_140_height.jpg",

"Violist_Painting_Red_Blue_140_height.jpg",

"Violist_Ready_Outside_Hold_by_el_140_height.jpg");

?>