
<!-- SiteSearch Google -->
<form method="get" action="http://arthurx.org/Search.php" target="_top">
<table border="0" bgcolor="#ffffff">
<tr><td nowrap="nowrap" valign="top" align="left" height="32">

<br/>
<input type="hidden" name="domains" value="arthurx.org"></input>
<label for="sbi" style="display: none"><font size="-1" color="#000000"></font></label>
<input type="text" name="q" size="20" maxlength="255" value="" id="sbi"></input>
<label for="sbb" style="display: none">Zoekformulier verzenden</label>
<input type="submit" name="sa" value="Search Google" id="sbb"></input>
</td></tr>
<tr>
<td nowrap="nowrap">
<table>
<tr>
<td>
<input type="radio" name="sitesearch" value="" checked id="ss0"></input>
<label for="ss0" title="Zoek op het internet"><font size="-1" color="#000000">Web</font></label></td>
<td>
<input type="radio" name="sitesearch" value="arthurx.org" id="ss1"></input>
<label for="ss1" title="Zoeken arthurx.org"><font size="-1" color="#000000">arthurx.org</font></label></td>
</tr>
</table>
<input type="hidden" name="client" value="pub-2079907996587686"></input>
<input type="hidden" name="forid" value="1"></input>
<input type="hidden" name="ie" value="ISO-8859-1"></input>
<input type="hidden" name="oe" value="ISO-8859-1"></input>
<input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:11"></input>
<input type="hidden" name="hl" value="nl"></input>
</td></tr></table>
</form>
<!-- SiteSearch Google -->


